name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set execute permissions on package_lambda.sh
      run: chmod +x lambda/package_lambda.sh

    - name: Run Lambda Packaging Script
      run: ./lambda/package_lambda.sh

    - name: Set execute permissions on package_layer.sh
      run: chmod +x lambda/package_layer.sh

    - name: Run Lambda Layer Packaging Script
      run: ./lambda/package_layer.sh

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Set execute permissions on terraform-import.sh
      run: chmod +x ./terraform-import.sh

    - name: Terraform Import Resources
      run: ./terraform-import.sh

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
